name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ose dega kryesore që përdorni

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ose versioni që ju duhet

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build  # komanda që ndërton faqen tuaj

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # ose dosja ku gjendet faqja statike
